### ISSUE TITLE
funasr pipeline 设定了gpu 也没跑在gpu上

### ISSUE THREAD

**Issue by panxin801** [RVC-Boss/GPT-SoVITS#285]
您好，感谢分享这么棒的工作。其中发现一个现象。
在cmd-asr.py 中使用pipeline 进行批量asr 推理的时候，没有用到gpu而是cpu 推理的。

```python3
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model=path_asr, model_revision="v2.0.4",
    vad_model=path_vad, vad_model_revision="v2.0.4",
    punc_model=path_punc, punc_model_revision="v2.0.4",
    device="cuda:4"
)
```
我的modelscope==1.11.1
funasr==1.0.3
torch==2.0.1+cu118

**Comment by LauraGPT** [comment]
`device=cuda`

**Comment by RVC-Boss** [comment]
@LauraGPT @panxin801 为啥我这没指定device但是可以用GPU跑，奇怪的。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/129054828/1b94fb96-28b1-4a4e-b7a2-8a5d55b2df8e)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/129054828/42af3c02-9998-4c34-96a9-958ceb42279d)

**Comment by LauraGPT** [comment]
> @LauraGPT @panxin801 为啥我这没指定device但是可以用GPU跑，奇怪的。 ![image](https://private-user-images.githubusercontent.com/129054828/300418155-1b94fb96-28b1-4a4e-b7a2-8a5d55b2df8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjQyNDAsIm5iZiI6MTcwNjUyMzk0MCwicGF0aCI6Ii8xMjkwNTQ4MjgvMzAwNDE4MTU1LTFiOTRmYjk2LTI4YjEtNGE0ZS1iN2EyLThhNWQ1NWIyZGY4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMDI1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjE2NTc0YWMzZjBlYTkwNTUxOTU0Yjk1MzQ3ZGQ4OTNjYjM2MTg4MjUwNWYyMWJlN2RiOGVhN2ZkMjFkNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l7bar7ZmBG_Ff-U6Kff9jJpif-Ii34RxvF0L4uLsxKI) ![image](https://private-user-images.githubusercontent.com/129054828/300418213-42af3c02-9998-4c34-96a9-958ceb42279d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjQyNDAsIm5iZiI6MTcwNjUyMzk0MCwicGF0aCI6Ii8xMjkwNTQ4MjgvMzAwNDE4MjEzLTQyYWYzYzAyLTk5OTgtNGMzNC05NmE5LTk1OGNlYjQyMjc5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMDI1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDBhM2YzM2I0ZjAwY2UzMDE4MmE0MGI1NTgxYmFlMjcyY2E4NmE5NjZlZmIyZWQ5NTA4ZGU5YmZhODI5MjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J_kOG1xxybPHG1xg9JAEkrSLpGqR1WmBfaror9sEXGQ)

GPU is the default device. If you set the device to cpu, the device would be cpu. The code is here: 

https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/auto/auto_model.py#L146

**Comment by panxin801** [comment]
@RVC-Boss 我看modelscope的文档 写的默认是 gpu
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/30232283/c620e7bf-2075-423e-9151-e65fc0fa6889)

链接在这https://modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E6%8E%A8%E7%90%86Pipeline

**Comment by RVC-Boss** [comment]
明白了，我后面传个参。

**Comment by panxin801** [comment]
> `device=cuda`

hello, sir. Following your advice, I change the code to 
```python
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model=path_asr, model_revision="v2.0.4",
    vad_model=path_vad, vad_model_revision="v2.0.4",
    punc_model=path_punc, punc_model_revision="v2.0.4",
    device="cuda" # Change here
)
```

it's not running on gpu either.

**Comment by LauraGPT** [comment]
> > `device=cuda`
> 
> hello, sir. Following your advice, I change the code to
> 
> ```python
> inference_pipeline = pipeline(
>     task=Tasks.auto_speech_recognition,
>     model=path_asr, model_revision="v2.0.4",
>     vad_model=path_vad, vad_model_revision="v2.0.4",
>     punc_model=path_punc, punc_model_revision="v2.0.4",
>     device="cuda" # Change here
> )
> ```
> 
> it's not running on gpu either.

Actually, it is a bug of funasr. We have fixed it in the commit:  https://github.com/alibaba-damo-academy/FunASR/commit/c47ad73e46bbaad7b2b003ecd890dc0e8f537172
Now, you could update funasr by:

```shell
git clone -b main--single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
pip install -e ./
```

**Comment by panxin801** [comment]
> 明白了，我后面传个参。

辛苦您，现在也能用，有了更更好哈哈哈。

**Comment by panxin801** [comment]
> > > `device=cuda`
> > 
> > 
> > hello, sir. Following your advice, I change the code to
> > ```python
> > inference_pipeline = pipeline(
> >     task=Tasks.auto_speech_recognition,
> >     model=path_asr, model_revision="v2.0.4",
> >     vad_model=path_vad, vad_model_revision="v2.0.4",
> >     punc_model=path_punc, punc_model_revision="v2.0.4",
> >     device="cuda" # Change here
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it's not running on gpu either.
> 
> Actually, it is a bug of funasr. We have fixed it in the commit: [alibaba-damo-academy/FunASR@c47ad73](https://github.com/alibaba-damo-academy/FunASR/commit/c47ad73e46bbaad7b2b003ecd890dc0e8f537172) Now, you could update funasr by:
> 
> ```shell
> git clone -b main --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
> pip install -e ./
> ```

Thank you for the update sir, but seems there's a bug still. In this commit and my env, gpu has mem occupation, but gpu utility is 0% still, and rtf are the same this cpu (cry face)

**Comment by R1ckShi** [comment]
> > > > `device=cuda`
> > > 
> > > 
> > > hello, sir. Following your advice, I change the code to
> > > ```python
> > > inference_pipeline = pipeline(
> > >     task=Tasks.auto_speech_recognition,
> > >     model=path_asr, model_revision="v2.0.4",
> > >     vad_model=path_vad, vad_model_revision="v2.0.4",
> > >     punc_model=path_punc, punc_model_revision="v2.0.4",
> > >     device="cuda" # Change here
> > > )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it's not running on gpu either.
> > 
> > 
> > Actually, it is a bug of funasr. We have fixed it in the commit: [alibaba-damo-academy/FunASR@c47ad73](https://github.com/alibaba-damo-academy/FunASR/commit/c47ad73e46bbaad7b2b003ecd890dc0e8f537172) Now, you could update funasr by:
> > ```shell
> > git clone -b main --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
> > pip install -e ./
> > ```
> 
> Thank you for the update sir, but seems there's a bug still. In this commit and my env, gpu has mem occupation, but gpu utility is 0% still, and rtf are the same this cpu (cry face)

Thanks a lot for using FunASR model, we've test the gpu using issue
it turns out that the acceleration of gpu (vs. cpu inference) shows obviously **only in two circumstance**:
1) the input wav is long thus the vad output periods can compose a larger batch (set batch_size_s)
2) decode multiple wavs at a time like using wav.scp as input (set batch_size)
if the wav input is short, the gpu accelerate might be not that obvious
we tested a 10 min wav with funasr
CPU, batch_size_s=1, rtf=0.123, time_escape=86.96s
GPU, batch_size_s=1, rtf=0.091, time_escape=64.00s
GPU, batch_size_s=300, rtf=0.005, time_escape=3.46s

In a word, if your wav is long, set batch_size_s=300 and it will be faster; if you have multiple wavs, use wav.scp as input and set batch_size=64 and is will be faster; if your wav is short, GPU time and CPU time will be similar and utility rise is hard to capture (ends quickly).

**Comment by panxin801** [comment]
> > > > > `device=cuda`
> > > > 
> > > > 
> > > > hello, sir. Following your advice, I change the code to
> > > > ```python
> > > > inference_pipeline = pipeline(
> > > >     task=Tasks.auto_speech_recognition,
> > > >     model=path_asr, model_revision="v2.0.4",
> > > >     vad_model=path_vad, vad_model_revision="v2.0.4",
> > > >     punc_model=path_punc, punc_model_revision="v2.0.4",
> > > >     device="cuda" # Change here
> > > > )
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > it's not running on gpu either.
> > > 
> > > 
> > > Actually, it is a bug of funasr. We have fixed it in the commit: [alibaba-damo-academy/FunASR@c47ad73](https://github.com/alibaba-damo-academy/FunASR/commit/c47ad73e46bbaad7b2b003ecd890dc0e8f537172) Now, you could update funasr by:
> > > ```shell
> > > git clone -b main --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
> > > pip install -e ./
> > > ```
> > 
> > 
> > Thank you for the update sir, but seems there's a bug still. In this commit and my env, gpu has mem occupation, but gpu utility is 0% still, and rtf are the same this cpu (cry face)
> 
> Thanks a lot for using FunASR model, we've tested the gpu using issue it turns out that the acceleration of gpu (vs. cpu inference) shows obviously **only in two circumstance**:
> 
> 1. the input wav is long thus the vad output periods can compose a larger batch (set batch_size_s)
> 2. decode multiple wavs at a time like using wav.scp as input (set batch_size)
> 
> if the wav input is short, the gpu accelerate might be not that obvious we tested a 10 min wav with funasr CPU, batch_size_s=1, rtf=0.123, time_escape=86.96s GPU, batch_size_s=1, rtf=0.091, time_escape=64.00s GPU, batch_size_s=300, rtf=0.005, time_escape=3.46s
> 
> In a word, if your wav is long, set batch_size_s=300 and it will be faster; if you have multiple wavs, use wav.scp as input and set batch_size=64 and is will be faster; if your wav is short, GPU time and CPU time will be similar and utility rise is hard to capture (ends quickly).

thank you sir for your careful analyse, I think may be there's something wrong with my wav files. thank you again
